Name: Gadisa Amenu

ID: UGR/8440/12


In [285]:
import torch

## Creating Layers

In [286]:
class DenseLayer:
  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = 0.01 * torch.rand(n_inputs, n_neurons)
    self.biases = torch.zeros((1, n_neurons))

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weights) + self.biases

## Activation Functions

### Linear

In [287]:
class Activation_Linear:
  # Forward pass
  def forward(self,input):
    self.output = input

In [288]:
x = Activation_Linear()
x.forward(torch.rand(2,3)-0.5)
x.output

tensor([[-0.3220,  0.0926,  0.0204],
        [ 0.1194,  0.1129, -0.2730]])

### ReLU

In [289]:
class Activation_ReLU:
  # Forward pass
  def forward(self, inputs):
    self.output = torch.max(torch.tensor(0),inputs)

In [290]:
x = Activation_ReLU()
x.forward(torch.rand(2,3)-0.5)
x.output

tensor([[0.0201, 0.3624, 0.3215],
        [0.0000, 0.0753, 0.0000]])

### Sigmoid

In [291]:
class Activation_Sigmoid:
  # Forward pass
  def forward(self, inputs):
    self.output = 1 / (1 + torch.exp(inputs*-1))

In [292]:
x = Activation_Sigmoid()
x.forward(torch.rand(2,3))
x.output

tensor([[0.6475, 0.7034, 0.5206],
        [0.5528, 0.6356, 0.5559]])

### Softmax

In [293]:
class Activation_Softmax:
  # Forward pass
  def forward(self, inputs):
    # Get unnormalized probabilities
    exp_values = torch.exp(inputs - torch.max(inputs, axis=1, keepdim=True).values)
    # Normalize them for each sample
    probabilities = exp_values / torch.sum(exp_values, axis=1, keepdim=True)
    self.output = probabilities

In [294]:
x = Activation_Softmax()
x.forward(torch.rand(2,3))
print(x.output)
print(torch.sum(x.output,axis=1,keepdim=True))

tensor([[0.2994, 0.4913, 0.2094],
        [0.3211, 0.3651, 0.3137]])
tensor([[1.0000],
        [1.0000]])



#### BackPropagation

In [295]:
X = torch.tensor([0.1, 0.5])
y = torch.tensor([0.04, 0.75])

In [296]:
hidden_layer_1 = DenseLayer(2, 4)
activation1 =  Activation_Sigmoid()
output_layer = DenseLayer(4, 2)
# activation2 = Activation_Linear()

In [297]:
def forward_pass(X):
  hidden_layer_1.forward(X)
  activation1.forward(hidden_layer_1.output)
  output_layer.forward(activation1.output)
  # activation2.forward(output_layer.output)
  return output_layer.output

In [298]:
def back_prop(fp):
  lr = torch.tensor(0.01)

  back1 = (-y[0] + fp[0][0])
  back2 = (-y[1] + fp[0][1])



  output_layer.weights[0][0] -= lr * back1*activation1.output[0][0]
  output_layer.weights[0][1] -= lr * back2*activation1.output[0][0]

  output_layer.weights[1][0] -= lr * back1*activation1.output[0][1]
  output_layer.weights[1][1] -= lr * back2*activation1.output[0][1]

  output_layer.weights[2][0] -= lr * back1*activation1.output[0][2]
  output_layer.weights[2][1] -= lr * back2*activation1.output[0][2]

  output_layer.weights[3][0] -= lr * back1*activation1.output[0][3]
  output_layer.weights[3][1] -= lr * back2*activation1.output[0][3]

  output_layer.biases[0][0] -= lr * back1
  output_layer.biases[0][1] -= lr * back2

  activation1_derivative_1 = activation1.output[0][0]*( 1 - activation1.output[0][0])
  activation1_derivative_2 = activation1.output[0][1]*( 1 - activation1.output[0][1])
  activation1_derivative_3 = activation1.output[0][2]*( 1 - activation1.output[0][2])
  activation1_derivative_4 = activation1.output[0][3]*( 1 - activation1.output[0][3])

  hidden_layer_1.weights[0][0] -= lr * (back1 * output_layer.weights[0][0] + back2 * output_layer.weights[0][1]) * activation1_derivative_1 * X[0]
  hidden_layer_1.weights[1][0] -= lr * (back1 * output_layer.weights[0][0] + back2 * output_layer.weights[0][1]) * activation1_derivative_1 * X[1]

  hidden_layer_1.weights[0][1] -= lr * (back1 * output_layer.weights[1][0] + back2 * output_layer.weights[1][1]) * activation1_derivative_2 * X[0]
  hidden_layer_1.weights[1][1] -= lr * (back1 * output_layer.weights[1][0] + back2 * output_layer.weights[1][1]) * activation1_derivative_2 * X[1]

  hidden_layer_1.weights[0][2] -= lr * (back1 * output_layer.weights[2][0] + back2 * output_layer.weights[2][1]) * activation1_derivative_3  * X[0]
  hidden_layer_1.weights[1][2] -= lr * (back1 * output_layer.weights[2][0] + back2 * output_layer.weights[2][1]) * activation1_derivative_3  * X[1]

  hidden_layer_1.weights[0][3] -= lr * (back1 * output_layer.weights[3][0] + back2 * output_layer.weights[3][1]) * activation1_derivative_4 * X[0]
  hidden_layer_1.weights[1][3] -= lr * (back1 * output_layer.weights[3][0] + back2 * output_layer.weights[3][1]) * activation1_derivative_4 * X[1]

  hidden_layer_1.biases[0][0] -= lr * (back1 * output_layer.weights[0][0] + back2 * output_layer.weights[0][1]) * activation1_derivative_1
  hidden_layer_1.biases[0][1] -= lr * (back1 * output_layer.weights[1][0] + back2 * output_layer.weights[1][1]) * activation1_derivative_2
  hidden_layer_1.biases[0][2] -= lr * (back1 * output_layer.weights[2][0] + back2 * output_layer.weights[2][1]) * activation1_derivative_3
  hidden_layer_1.biases[0][3] -= lr * (back1 * output_layer.weights[3][0] + back2 * output_layer.weights[3][1]) * activation1_derivative_4



In [299]:
def error_calculation(y_true, y_pred):
  return torch.mean(0.5*(y_true - y_pred)**2)

In [300]:
loss = 0.0001

In [301]:
y_pred = forward_pass(X)
err = error_calculation(y, y_pred)
print("Initial loss:", err)
print("Initial prediction:",y_pred)
while err > loss:
  back_prop(y_pred)
  y_pred = forward_pass(X)
  err = error_calculation(y, y_pred)

print("Final loss:", err)
print("Final prediction:",y_pred)
print("Target value:",y)

Initial loss: tensor(0.1381)
Initial prediction: tensor([[0.0090, 0.0075]])
Final loss: tensor(9.7415e-05)
Final prediction: tensor([[0.0392, 0.7303]])
Target value: tensor([0.0400, 0.7500])
